# -*- coding: utf-8 -*-
"""project120.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MYhC87Ao5ce8KctLrUgnKIBUlVXhO6fF
"""

from sklearn import datasets

wine=datasets.load_wine()

print('Features',wine.feature_names)
print('Labels',wine.target_names)

from sklearn.model_selection import train_test_split

X=wine.data
Y=wine.target

X_train1,X_test1,Y_train1,Y_test1=train_test_split(X,Y,test_size=0.25,random_state=42)

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

X_train1=sc.fit_transform(X_train1)
X_test1=sc.fit_transform(X_test1)

model1=GaussianNB()
model1.fit(X_train1,Y_train1)

y_pred1=model1.predict(X_test1)
accuracy=accuracy_score(Y_test1,y_pred1)
print(accuracy)